/**
 * Detecting a pasted HTML document.
 *
 * The user's source is an LLM-generated HTML report, copied as *source text*
 * from a chat UI — so the clipboard carries only `text/plain`, whose content
 * starts with a doctype or an `<html>` tag. That makes detection almost
 * unambiguous: no need to inspect the `text/html` flavour or cope with the many
 * shapes Word and web pages produce.
 *
 * Kept deliberately narrow. A false positive would route ordinary prose into the
 * HTML document path, which is far more disruptive than a false negative (that
 * merely leaves today's behaviour in place).
 */

/** Leading comments and whitespace carry no signal; skip them before matching. */
function stripLeadingNoise(text: string): string {
  let out = text.trimStart()
  // A doctype is often preceded by a licence or "generated by" comment.
  while (out.startsWith('<!--')) {
    const end = out.indexOf('-->')
    if (end === -1) break
    out = out.slice(end + 3).trimStart()
  }
  return out
}

/**
 * Is this text a standalone HTML document?
 *
 * Requires a doctype or an `<html>` root — a bare fragment such as
 * `<div>…</div>` deliberately does NOT qualify, because a fragment belongs in
 * the rich-text path where it stays editable.
 */
export function isHtmlDocument(text: string): boolean {
  if (!text) return false
  const head = stripLeadingNoise(text).slice(0, 200).toLowerCase()
  if (head.startsWith('<!doctype html')) return true
  // `<html`, optionally with attributes: <html lang="zh">
  return /^<html[\s>]/.test(head)
}

/**
 * Does this text contain a `<body>` or `<head>`? Used only to describe the
 * payload to the user, not to decide routing.
 */
export function hasDocumentStructure(text: string): boolean {
  return /<body[\s>]/i.test(text) || /<head[\s>]/i.test(text)
}

/** Extract the document title, for naming a new document. */
export function htmlDocumentTitle(text: string): string | null {
  const match = text.match(/<title[^>]*>([\s\S]*?)<\/title>/i)
  if (!match) return null
  const title = match[1]
    .replace(/<[^>]*>/g, '')
    .replace(/\s+/g, ' ')
    .trim()
  return title || null
}

/**
 * Plain text of an HTML document, for the search index.
 *
 * Backend full-text search reads content_md, and an HTML document has no
 * meaningful markdown — without this it would be unfindable. Parsed in a
 * detached document so nothing executes and nothing is fetched.
 */
export function htmlToPlainText(html: string): string {
  if (!html) return ''
  const doc = new DOMParser().parseFromString(html, 'text/html')
  for (const el of Array.from(doc.querySelectorAll('script, style, noscript, template'))) {
    el.remove()
  }
  const text = doc.body?.textContent ?? ''
  return text.replace(/[ \t]+/g, ' ').replace(/\n{3,}/g, '\n\n').trim()
}
